---
abstract: 'Simple TreePath'
author:
  - 'Daniel Brosseau <dab@catapulse.org>'
build_requires:
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: TreePath
requires:
  Config::JFDI: '0'
  DBIx::Class: '0.082810'
  Moose: '2.0402'
  MooseX::Object::Pluggable: '0.0013'
  UNIVERSAL::require: '0.17'
  YAML: '1.13'
version: '0.08'
